on: [push, pull_request]
name: Test
jobs:
  test:
    services:
      etcd:
        image: bitnami/etcd:3.4.16
        ports:
          - 2379:2379
        env:
          ALLOW_NONE_AUTHENTICATION: 'yes'
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Vendor
      run: |
        go mod vendor
    - name: Test
      run: |
        go test -mod vendor -cover .
    - name: Test etcd
      env:
        ETCD_HOST: etcd:2379
      run: |
        cd storages/etcd
        go test -mod vendor -cover .
